'' Dark theme for PlantUML diagrams on docs.jitterbit.com
<style>
element {
  ebnf {
    LineColor black
    Fontcolor black
    Backgroundcolor blanchedalmond
    note {
      Backgroundcolor red
    }
  }
}
</style>
